/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.syeedode.datastructures.linkedlist.a_printlinklist;

import com.syeedode.datastructures.linkedlist.Node;

public class LinkedListMain {

    /**
     *
     * @param args
     *
     * 11, 1, 5, 7, 1, 3, 10
     */
    public static void main(String [] args) {
        Node linkListNode = new Node(11);
        linkListNode.appendToTail(1);
        linkListNode.appendToTail(5);
        linkListNode.appendToTail(7);
        linkListNode.appendToTail(7);
        linkListNode.appendToTail(1);
        linkListNode.appendToTail(3);
        linkListNode.appendToTail(10);

        linkListNode.printList();

    }
}
