/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.syeedode.datastructures;

import com.syeedode.datastructures.linkedlist.a_printlinklist.LinkedListMain;
import org.junit.Test;

public class LinkedListMainTest {

    @Test
    public void testSomeLibraryMethod() {
        LinkedListMain classUnderTest = new LinkedListMain();
        // assertTrue("main should return 'true'", classUnderTest.main());
    }
}
